
 

version: "3.4"
services:
  app:
    container_name: commerce
    image: commerce
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000