name: GitHub Actions Demo
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '16.16.0'
          cache: 'yarn'
      

      - name: Install dependencies
        run: yarn install

      - name: Build dependencies
        run: yarn build

      - name: Test dependencies
        run: yarn test

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

